// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID             pgtype.UUID
	GroupID        pgtype.UUID
	Title          string
	Description    pgtype.Text
	Amount         pgtype.Numeric
	SplitType      string
	TaxAmount      pgtype.Numeric
	DiscountAmount pgtype.Numeric
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type ExpenseItem struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	Name      string
	Amount    pgtype.Numeric
}

type ExpenseItemSplit struct {
	ID            pgtype.UUID
	ExpenseItemID pgtype.UUID
	MemberID      pgtype.UUID
}

type ExpensePayment struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	MemberID  pgtype.UUID
	Amount    pgtype.Numeric
}

type ExpenseSplit struct {
	ID        pgtype.UUID
	ExpenseID pgtype.UUID
	MemberID  pgtype.UUID
	Amount    pgtype.Numeric
}

type Group struct {
	ID          pgtype.UUID
	Name        string
	Description string
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type GroupMember struct {
	ID        pgtype.UUID
	GroupID   pgtype.UUID
	Name      string
	IsOwner   bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	FullName     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
