// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, title, description, amount, split_type, tax_amount, discount_amount, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, group_id, title, description, amount, split_type, tax_amount, discount_amount, metadata, created_at
`

type CreateExpenseParams struct {
	GroupID        pgtype.UUID
	Title          string
	Description    pgtype.Text
	Amount         pgtype.Numeric
	SplitType      string
	TaxAmount      pgtype.Numeric
	DiscountAmount pgtype.Numeric
	Metadata       []byte
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.SplitType,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.Metadata,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.SplitType,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createExpenseItem = `-- name: CreateExpenseItem :one
INSERT INTO expense_items (expense_id, name, amount)
VALUES ($1, $2, $3)
RETURNING id, expense_id, name, amount
`

type CreateExpenseItemParams struct {
	ExpenseID pgtype.UUID
	Name      string
	Amount    pgtype.Numeric
}

func (q *Queries) CreateExpenseItem(ctx context.Context, arg CreateExpenseItemParams) (ExpenseItem, error) {
	row := q.db.QueryRow(ctx, createExpenseItem, arg.ExpenseID, arg.Name, arg.Amount)
	var i ExpenseItem
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.Name,
		&i.Amount,
	)
	return i, err
}

const createExpenseItemSplit = `-- name: CreateExpenseItemSplit :one
INSERT INTO expense_item_splits (expense_item_id, member_id)
VALUES ($1, $2)
RETURNING id, expense_item_id, member_id
`

type CreateExpenseItemSplitParams struct {
	ExpenseItemID pgtype.UUID
	MemberID      pgtype.UUID
}

func (q *Queries) CreateExpenseItemSplit(ctx context.Context, arg CreateExpenseItemSplitParams) (ExpenseItemSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseItemSplit, arg.ExpenseItemID, arg.MemberID)
	var i ExpenseItemSplit
	err := row.Scan(&i.ID, &i.ExpenseItemID, &i.MemberID)
	return i, err
}

const createExpensePayment = `-- name: CreateExpensePayment :one
INSERT INTO expense_payments (expense_id, member_id, amount)
VALUES ($1, $2, $3)
RETURNING id, expense_id, member_id, amount
`

type CreateExpensePaymentParams struct {
	ExpenseID pgtype.UUID
	MemberID  pgtype.UUID
	Amount    pgtype.Numeric
}

func (q *Queries) CreateExpensePayment(ctx context.Context, arg CreateExpensePaymentParams) (ExpensePayment, error) {
	row := q.db.QueryRow(ctx, createExpensePayment, arg.ExpenseID, arg.MemberID, arg.Amount)
	var i ExpensePayment
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.MemberID,
		&i.Amount,
	)
	return i, err
}

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (expense_id, member_id, amount)
VALUES ($1, $2, $3)
RETURNING id, expense_id, member_id, amount
`

type CreateExpenseSplitParams struct {
	ExpenseID pgtype.UUID
	MemberID  pgtype.UUID
	Amount    pgtype.Numeric
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit, arg.ExpenseID, arg.MemberID, arg.Amount)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.MemberID,
		&i.Amount,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner_id, created_at, updated_at
`

type CreateGroupParams struct {
	Name        string
	Description string
	OwnerID     pgtype.UUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, arg.Name, arg.Description, arg.OwnerID)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (group_id, name, is_owner)
VALUES ($1, $2, $3)
RETURNING id, group_id, name, is_owner, created_at
`

type CreateGroupMemberParams struct {
	GroupID pgtype.UUID
	Name    string
	IsOwner bool
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember, arg.GroupID, arg.Name, arg.IsOwner)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.IsOwner,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, full_name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	FullName     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.FullName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND group_id = $2
`

type DeleteExpenseParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.GroupID)
	return err
}

const deleteExpenseItems = `-- name: DeleteExpenseItems :exec
DELETE FROM expense_items WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseItems(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseItems, expenseID)
	return err
}

const deleteExpensePayments = `-- name: DeleteExpensePayments :exec
DELETE FROM expense_payments WHERE expense_id = $1
`

func (q *Queries) DeleteExpensePayments(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpensePayments, expenseID)
	return err
}

const deleteExpenseSplits = `-- name: DeleteExpenseSplits :exec
DELETE FROM expense_splits WHERE expense_id = $1
`

func (q *Queries) DeleteExpenseSplits(ctx context.Context, expenseID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpenseSplits, expenseID)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1 AND owner_id = $2
`

type DeleteGroupParams struct {
	ID      pgtype.UUID
	OwnerID pgtype.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.OwnerID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, group_id, title, description, amount, split_type, tax_amount, discount_amount, metadata, created_at
FROM expenses
WHERE id = $1 AND group_id = $2 LIMIT 1
`

type GetExpenseByIDParams struct {
	ID      pgtype.UUID
	GroupID pgtype.UUID
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.GroupID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.SplitType,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseItemSplitsByItemID = `-- name: GetExpenseItemSplitsByItemID :many
SELECT id, expense_item_id, member_id
FROM expense_item_splits
WHERE expense_item_id = $1
`

func (q *Queries) GetExpenseItemSplitsByItemID(ctx context.Context, expenseItemID pgtype.UUID) ([]ExpenseItemSplit, error) {
	rows, err := q.db.Query(ctx, getExpenseItemSplitsByItemID, expenseItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseItemSplit
	for rows.Next() {
		var i ExpenseItemSplit
		if err := rows.Scan(&i.ID, &i.ExpenseItemID, &i.MemberID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseItemsByExpenseID = `-- name: GetExpenseItemsByExpenseID :many
SELECT id, expense_id, name, amount
FROM expense_items
WHERE expense_id = $1
`

func (q *Queries) GetExpenseItemsByExpenseID(ctx context.Context, expenseID pgtype.UUID) ([]ExpenseItem, error) {
	rows, err := q.db.Query(ctx, getExpenseItemsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseItem
	for rows.Next() {
		var i ExpenseItem
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.Name,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensePaymentsByExpenseID = `-- name: GetExpensePaymentsByExpenseID :many
SELECT id, expense_id, member_id, amount
FROM expense_payments
WHERE expense_id = $1
`

func (q *Queries) GetExpensePaymentsByExpenseID(ctx context.Context, expenseID pgtype.UUID) ([]ExpensePayment, error) {
	rows, err := q.db.Query(ctx, getExpensePaymentsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpensePayment
	for rows.Next() {
		var i ExpensePayment
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.MemberID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpenseSplitsByExpenseID = `-- name: GetExpenseSplitsByExpenseID :many
SELECT id, expense_id, member_id, amount
FROM expense_splits
WHERE expense_id = $1
`

func (q *Queries) GetExpenseSplitsByExpenseID(ctx context.Context, expenseID pgtype.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, getExpenseSplitsByExpenseID, expenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.MemberID,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpensesByGroupID = `-- name: GetExpensesByGroupID :many
SELECT id, group_id, title, description, amount, split_type, tax_amount, discount_amount, metadata, created_at
FROM expenses
WHERE group_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetExpensesByGroupID(ctx context.Context, groupID pgtype.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, getExpensesByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Title,
			&i.Description,
			&i.Amount,
			&i.SplitType,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, owner_id, created_at, updated_at
FROM groups
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupMembersByGroupID = `-- name: GetGroupMembersByGroupID :many
SELECT id, group_id, name, is_owner, created_at
FROM group_members
WHERE group_id = $1
ORDER BY is_owner DESC, created_at ASC
`

func (q *Queries) GetGroupMembersByGroupID(ctx context.Context, groupID pgtype.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, getGroupMembersByGroupID, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.IsOwner,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByOwnerID = `-- name: GetGroupsByOwnerID :many
SELECT id, name, description, owner_id, created_at, updated_at
FROM groups
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetGroupsByOwnerID(ctx context.Context, ownerID pgtype.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, getGroupsByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, created_at, updated_at
FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET title = $3, description = $4, amount = $5, split_type = $6, tax_amount = $7, discount_amount = $8, metadata = $9
WHERE id = $1 AND group_id = $2
RETURNING id, group_id, title, description, amount, split_type, tax_amount, discount_amount, metadata, created_at
`

type UpdateExpenseParams struct {
	ID             pgtype.UUID
	GroupID        pgtype.UUID
	Title          string
	Description    pgtype.Text
	Amount         pgtype.Numeric
	SplitType      string
	TaxAmount      pgtype.Numeric
	DiscountAmount pgtype.Numeric
	Metadata       []byte
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.GroupID,
		arg.Title,
		arg.Description,
		arg.Amount,
		arg.SplitType,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.Metadata,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Title,
		&i.Description,
		&i.Amount,
		&i.SplitType,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
